
language: csharp
solution: ChamberLib.sln

addons:
  apt:
    packages:
      - nunit-console

script:
  - nuget restore ChamberLib.sln
  - xbuild /p:Configuration=Debug ChamberLib.sln
  - nunit-console ./ChamberLibTests/bin/Debug/ChamberLibTests.dll

branches:
  only:
    - master

